force-app/main/default/objects/Contact/fields/Points_Ammount__c.field-meta.xml
<CustomField>
    <fullName>Points_Ammount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/Task_Monitor__c.object-meta.xml
<CustomObject>
    <label>Task Monitor</label>
    <nameField>
        <label>Task Monitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks Monitor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Monitor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tasks Monitor</relationshipLabel>
    <relationshipName>Tasks_Monitor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Difficulty__c</fullName>
    <label>Difficulty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trivial</fullName>
            </value>
            <value>
                <fullName>Easy</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Hard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Habit_Complete__c.field-meta.xml
<CustomField>
    <fullName>Habit_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Habit Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Due Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TO-DO</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Habit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
	
    public static Id insertTaskMonitor_Habit_New (){
        Contact cont = new Contact(LastName = 'Last Name Test');
        insert cont;
        Task_Monitor__c task = new Task_Monitor__c(Name = 'Task',
                                                   Contact__c = cont.Id,
                                                   Difficulty__c = 'Hard',
                                                   Type__c = 'Habit',
                                                   State__c = 'New');
        Database.SaveResult result = Database.insert(task, false);
        return task.Id;
    }
    
    public static Id insertTaskMonitor_Daily_New (){
        Contact cont = new Contact(LastName = 'Last Name Test');
        insert cont;
        Task_Monitor__c task = new Task_Monitor__c(Name = 'Task',
                                                   Contact__c = cont.Id,
                                                   Difficulty__c = 'Hard',
                                                   Type__c = 'Daily',
                                                   State__c = 'New');
        Database.SaveResult result = Database.insert(task, false);
        return task.Id;
    }
    
    public static Id insertTaskMonitor_Habit_New_For_Contact (){
        Contact cont = new Contact(LastName = 'Last Name Test',Points_Ammount__c = 0);
        insert cont;
        Task_Monitor__c task = new Task_Monitor__c(Name ='Task',
                                                   Contact__c = cont.Id,
                                                   Difficulty__c = 'Hard',
                                                   Type__c = 'Habit',
                                                   State__c = 'New');
        Database.SaveResult result = Database.insert(task, false);
        HABIT_TASKController.updateContactAmountOfPoints(task.Id, true);
        return cont.Id;
    }
    
    public static Id dataFor_TestUpdateTODOType(){
        // Test data setup
        // Create a contact and test the task is created properly and the contact amaunt is updated
        Contact cont = new Contact(LastName ='Last Name Test');
        insert cont;
        Task_Monitor__c task = new Task_Monitor__c(Name ='Task1',
                                                   Contact__c = cont.Id,
                                                   Difficulty__c = 'Hard',
                                                   Type__c = 'TO-DO',
                                                   State__c = 'Completed');
        Database.SaveResult result = Database.insert(task, false);
        return cont.Id;
    }
    public static Id dataFor_TestTO_DO_Overdue(){
        // Test data setup
        // Create a contact and test the task is created properly and the contact amaunt is updated
        Contact cont = new Contact(LastName ='Last Name Test');
        insert cont;
         Task_Monitor__c task = new Task_Monitor__c(Name = 'Task',
                                                   Contact__c = cont.Id,
                                                   Difficulty__c = 'Hard',
                                                   Due_Date__c = Date.today().addDays(-1),
                                                   Type__c = 'TO-DO',
                                                   State__c = 'Completed');
        Database.SaveResult result = Database.insert(task, false);
        return cont.Id;
    }
    
    public static Id dataFor_TestUpdateDailyType(){
        // Test data setup
        // Create a contact and test the task is created properly and the contact amaunt is updated
        Contact cont = new Contact(LastName ='Last Name Test');
        insert cont;
        Task_Monitor__c task = new Task_Monitor__c(Name = 'Task1',
                                                   Contact__c = cont.Id,
                                                   Difficulty__c = 'Hard',
                                                   Type__c = 'Daily',
                                                   State__c = 'Completed');
        Database.SaveResult result = Database.insert(task, false);
        return cont.Id;
    }
	
    
    public static List<Id> insertTaskMonitorOfType_Habit_Daily_Not_New_For_Contact(integer numberOfHabits, integer numberOfDaily){
        
        Contact cont = new Contact(LastName ='Last Name Test');
        List<Task_Monitor__c> tasks = new List<Task_Monitor__c>();
		insert cont;        
        for(integer i=0; i < numberOfHabits; i++){
            Task_Monitor__c taskHabit;
            if(math.mod(i, 2) == 0)
            	taskHabit = new Task_Monitor__c(Name ='Task' + i,
                                           Contact__c = cont.Id,
                                           Type__c = 'Habit',
                                           State__c = 'Completed',
                                           Habit_Complete__c = true);
            else
               taskHabit = new Task_Monitor__c(Name ='Task' + i,
                                          Contact__c = cont.Id,
                                          Type__c = 'Habit',
                                          State__c = 'In Progress',
                                          Habit_Complete__c = false);
            tasks.add(taskHabit);
        }
        for(integer i=0; i < numberOfDaily; i++){
            Task_Monitor__c taskDaily;
            if(math.mod(i, 2) == 0)
            	taskDaily = new Task_Monitor__c(Name ='Task',
                                                Contact__c =cont.Id,
                                                Difficulty__c ='Hard',
                                                Type__c ='Daily',
                                                State__c ='Completed');
            else
               taskDaily = new Task_Monitor__c(Name ='Task',
                                                   Contact__c =cont.Id,
                                                   Difficulty__c ='Hard',
                                                   Type__c ='Daily',
                                                   State__c ='In Progress');
            tasks.add(taskDaily);
        }
        
        insert tasks;
        
        // Get the IDs just inserted
        Map<Id, Task_Monitor__c> tasksMap = new Map<Id, Task_Monitor__c>(tasks);
        List<Id> tasksIds = new List<Id>(tasksMap.keySet());
        return tasksIds;
    }

}