force-app/main/default/objects/Contact/fields/Points_Ammount__c.field-meta.xml
<CustomField>
    <fullName>Points_Ammount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/Task_Monitor__c.object-meta.xml
<CustomObject>
    <label>Task Monitor</label>
    <nameField>
        <label>Task Monitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks Monitor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Monitor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tasks Monitor</relationshipLabel>
    <relationshipName>Tasks_Monitor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Difficulty_val__c.field-meta.xml
<CustomField>
    <fullName>Difficulty_val__c</fullName>
    <formula>Case(Difficulty__c,&quot;Trivial&quot;,2,&quot;Easy&quot;,3,&quot;Medium&quot;,4,&quot;Hard&quot;,5,1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Difficulty val</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TO-DO</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Habit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AlterAmountEmployeeHandler.cls
public with sharing  class AlterAmountEmployeeHandler {
    public static Contact handleContact(Contact cont)
    {
        for(integer i = 0; i < cont.Tasks_Monitor__r.size(); i++){
            decimal points = Math_Util.Fibonacci_Serie(cont.Tasks_Monitor__r[i].Difficulty_val__c);
            if(cont.Tasks_Monitor__r[i].Type__c == 'TO-DO'){
                if(cont.Tasks_Monitor__r[i].Due_Date__c <> null && cont.Tasks_Monitor__r[i].Due_Date__c < system.today())
                {//its overdue
                    cont.Points_Ammount__c -= points/2;
                }
                else{
                    cont.Points_Ammount__c += points;
                }
            }
            else //daily
                cont.Points_Ammount__c += points/2;
        }
        return cont;
    }
}