force-app/main/default/objects/Contact/fields/Points_Ammount__c.field-meta.xml
<CustomField>
    <fullName>Points_Ammount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/Task_Monitor__c.object-meta.xml
<CustomObject>
    <label>Task Monitor</label>
    <nameField>
        <label>Task Monitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks Monitor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Monitor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tasks Monitor</relationshipLabel>
    <relationshipName>Tasks_Monitor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Difficulty_val__c.field-meta.xml
<CustomField>
    <fullName>Difficulty_val__c</fullName>
    <formula>Case(Difficulty__c,&quot;Trivial&quot;,2,&quot;Easy&quot;,3,&quot;Medium&quot;,4,&quot;Hard&quot;,5,1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Difficulty val</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Habit_Complete__c.field-meta.xml
<CustomField>
    <fullName>Habit_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Habit Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Points_Awarded__c.field-meta.xml
<CustomField>
    <fullName>Points_Awarded__c</fullName>
    <label>Points Awarded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Due Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TO-DO</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Habit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResetDailyHabitTasks.cls
//Reset the states of daily and habit task and add the resulted points to the employee
global class ResetDailyHabitTasks implements Schedulable {
    global void execute(SchedulableContext ctx) {
        
        try{
             List<Contact> conts= new List<Contact>();//Not work ask why
             List<Task_Monitor__c> toUpdateTasks= new List<Task_Monitor__c>();//Not work ask why
           for(Contact cont : [SELECT Id, Points_Ammount__c, //Select contacts with daily and habit tasks
                            	(Select 
                                 State__c, Type__c, Habit_Complete__c,
                                 Difficulty_val__c, Points_Awarded__c
                                 from Tasks_Monitor__r where  Type__c <>'TO-DO') 
                               FROM Contact where Id  IN (SELECT Contact__c FROM Task_Monitor__c 
                               where  Type__c <>'TO-DO')])
            {
                //Calcule the points and update the 
                for(integer i = 0; i < cont.Tasks_Monitor__r.size(); i++){
                    Task_Monitor__c task = cont.Tasks_Monitor__r[i];
                    if(task.Type__c == 'Daily'){
                        if(task.State__c=='Completed'){
                            cont.Points_Ammount__c += task.Points_Awarded__c;
                        }
                        else{
                             //Calculate the fibonacci result with auxiliary class
                             cont.Points_Ammount__c -= Math_Util.Fibonacci_Serie(task.Difficulty_val__c)/2;
                        }
                    }
                    else{ //Habit
                        if(task.Habit_Complete__c)
                            cont.Points_Ammount__c += task.Points_Awarded__c;
                        else
                            cont.Points_Ammount__c -= task.Points_Awarded__c;                        
                    }
                   
                    //always reset the state
                    if(task.State__c <> 'New')
                    	task.State__c = 'New';
                    
                    toUpdateTasks.add(task);
                }
                 conts.add(cont);
            }
            update toUpdateTasks;
            update conts;   
        }
        catch(System.Exception ex){
            System.debug(ex.getMessage());
        }
    }
}