force-app/main/default/objects/Contact/fields/Points_Ammount__c.field-meta.xml
<CustomField>
    <fullName>Points_Ammount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/Task_Monitor__c.object-meta.xml
<CustomObject>
    <label>Task Monitor</label>
    <nameField>
        <label>Task Monitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks Monitor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Monitor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tasks Monitor</relationshipLabel>
    <relationshipName>Tasks_Monitor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Difficulty__c</fullName>
    <label>Difficulty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trivial</fullName>
            </value>
            <value>
                <fullName>Easy</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Hard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Due Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TO-DO</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Habit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDashBoardComponent.cls
@isTest
public class TestDashBoardComponent {
	 @isTest static void TestgetHabit_Tasks(){
        Contact cont = new Contact(LastName = 'Last Name Test');
        insert cont;
        Task_Monitor__c task = new Task_Monitor__c(Name = 'Task',
                                                   Contact__c = cont.Id,
                                                   Difficulty__c = 'Hard',
                                                   Type__c = 'Habit',
                                                   State__c = 'New');
         // Perform test
        Test.startTest();
        Database.SaveResult result = Database.insert(task, false);
        Test.stopTest();
        // Verify 
         boolean res=false;
         for(Task_Monitor__c taskIterator : DashBoardController.getHabit_Tasks()){
             if(task.Id == taskIterator.Id){
                 res = true;
             }
         }
         System.assert(res == true,'The data do not returned properly');
    }
    @isTest static void TestgetDaily_AND_Todo_Tasks(){
        Contact cont = new Contact(LastName = 'Last Name Test');
        insert cont;
        Task_Monitor__c task = new Task_Monitor__c(Name = 'Task',
                                                   Contact__c = cont.Id,
                                                   Difficulty__c = 'Hard',
                                                   Type__c = 'Daily',
                                                   State__c = 'New');
         // Perform test
        Test.startTest();
        Database.SaveResult result = Database.insert(task, false);
        Test.stopTest();
        // Verify 
         boolean res=false;
         for(Task_Monitor__c taskIterator : DashBoardController.getDaily_AND_Todo_Tasks()){
             if(task.Id == taskIterator.Id){
                 res = true;
             }
         }
         System.assert(res == true,'The data do not returned properly');
    }
	@isTest static void TestupdateContactAmountOfPoints(){
        Contact cont = new Contact(LastName='Last Name Test',Points_Ammount__c = 0);
        insert cont;
        Task_Monitor__c task = new Task_Monitor__c(Name ='Task',
                                                   Contact__c = cont.Id,
                                                   Difficulty__c = 'Hard',
                                                   Type__c = 'Habit',
                                                   State__c = 'New');
         // Perform test
        Test.startTest();
        Database.SaveResult result = Database.insert(task, false);
         HABIT_TASKController.updateContactAmountOfPoints(task.Id, true);
        Test.stopTest();
        // Verify 
        Contact updatedCont= [Select Points_Ammount__c From Contact where Id = :cont.Id];
        System.assert(updatedCont.Points_Ammount__c == 1,'The points not where added properlly');
    }
}