force-app/main/default/objects/Contact/fields/Points_Ammount__c.field-meta.xml
<CustomField>
    <fullName>Points_Ammount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/Task_Monitor__c.object-meta.xml
<CustomObject>
    <label>Task Monitor</label>
    <nameField>
        <label>Task Monitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks Monitor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Monitor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tasks Monitor</relationshipLabel>
    <relationshipName>Tasks_Monitor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HABIT_TASKController.cls
public with sharing class HABIT_TASKController {
	@AuraEnabled
    public static void updateContactAmountOfPoints(String taskID,boolean addPoints) {
        // Check Contact fields that will be updated
    	String [] contactUpdateFields = new String [] {'Points_Ammount__c'};
        if( SecurityHandler.canUpdateContactFields(contactUpdateFields)){
            Contact cont = [SELECT Points_Ammount__c FROM Contact WHERE 
                            Id  IN (SELECT Contact__c FROM Task_Monitor__c 
                            where  Id = :taskID)];
            // I don't know why must be the assigment here.
            cont.Points_Ammount__c = addPoints ? ++cont.Points_Ammount__c : --cont.Points_Ammount__c; 
            update cont;      
        }
           
    }
}