force-app/main/default/objects/Task_Monitor__c/Task_Monitor__c.object-meta.xml
<CustomObject>
    <label>Task Monitor</label>
    <nameField>
        <label>Task Monitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks Monitor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Monitor__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Due Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Monitor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TO-DO</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Habit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DashBoardController.cls
public with sharing class DashBoardController {
	@AuraEnabled
    public static List<Task_Monitor__c> getDaily_AND_Todo_Tasks() {
        // Check Task_Monitor fields that will be updated
    	String [] tasktAccesFields = new String [] {'State__c','Type__c'};
        if(SecurityHandler.canAccesTask_MonitorFields(tasktAccesFields))
        	return [SELECT Id, State__c,Type__c FROM Task_Monitor__c where State__c <> 'Completed' and Type__c <> 'Habit'];
        return new List<Task_Monitor__c>();
    }
     
    @AuraEnabled
    public static List<Task_Monitor__c> getHabit_Tasks() {
        String [] tasktAccesFields = new String [] {'Id'};
        if(SecurityHandler.canAccesTask_MonitorFields(tasktAccesFields))
        	return [SELECT Id FROM Task_Monitor__c where Type__c ='Habit'];
        return new List<Task_Monitor__c>();
    }
}