force-app/main/default/objects/Task_Monitor__c/Task_Monitor__c.object-meta.xml
<CustomObject>
    <label>Task Monitor</label>
    <nameField>
        <label>Task Monitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks Monitor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Monitor__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Due Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestResetTasks.cls
@isTest
private class TestResetTasks {
    // Dummy CRON expression: almost midnight every day.
    // Because this is a test, job executes
    // immediately after Test.stopTest().
    public static String CRON_EXP = '0 59 23 * * ? *';
    static testmethod void testScheduledJob() {
        
        Test.startTest();
         	List<Id> tasksIds = TestDataFactory.insertTaskMonitorOfType_Habit_Daily_Not_New_For_Contact(149,50);
            // Schedule the test job
            String jobId = System.schedule('ScheduledApexTest',
                                           CRON_EXP, 
                                           new ResetDailyHabitTasks());         
        Test.stopTest();
        // Now that the scheduled job has executed,
        // check that our tasks were created
        List<Task_Monitor__c> lt = [SELECT Id,State__c 
              FROM Task_Monitor__c 
              WHERE Id IN :tasksIds];
        System.assertEquals(tasksIds.size(), lt.size(), 'Tasks were not created');
        List <Task_Monitor__c> resultTask= [Select Id From Task_Monitor__c where Id IN :tasksIds and State__c ='New' ];
        System.assertEquals(tasksIds.size(), resultTask.size(), 'Tasks states where not updated');
    }
}